pipeline {   
    agent any

    environment {
        IMAGE_NAME = "mydockerapp"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                docker stop $IMAGE_NAME || true
                docker rm $IMAGE_NAME || true
                docker run -d -p 8085:80 --name mydockerapp mydockerapp

                '''
            }
        }
    }

    post {
        success {
            echo "Docker image built and container is running at http://localhost:8080"
        }
        failure {
            echo "Build failed!"
        }
    }
}


